module.exports = function (server) {
  server.get('/info', function (req, res, next) {
    const info = {
      name: 'TodoApp',
      version: '1.0.0',
      description: 'Simple To-Do application API built with Node.js and Express',
      author: 'Generated by ChatGPT'
    };

    res.status(200).json(info);
    next();
  });
};
